/// This file is automatically generated. Do not change, modifications will be overwritten.

#pragma once

namespace events {


    // GlobalTriggers.xml


    // DefaultEvents.xml
    // PunishCustomer.lua: EventNoPay
    constexpr const char* CUSTOMER_NO_PAY = "customer:no-pay";

    // PunishCustomer.lua: EventCheat
    constexpr const char* CUSTOMER_GAMBLING_CHEAT = "customer:gambling-cheat";

    // RivalLose.lua: Event
    constexpr const char* RIVAL_LOST = "rival-lost";

    // Intro.lua: RunIntro
    constexpr const char* INTRO = "intro";



    // DefaultGirl.xml
    // MeetArenaTry.lua: MeetArena
    constexpr const char* GIRL_MEET_ARENA = "girl:meet:arena";

    // MeetTownDefault.lua: MeetTown
    constexpr const char* GIRL_MEET_TOWN = "girl:meet:town";

    // MeetCastingTry.lua: MeetCasting
    constexpr const char* GIRL_MEET_STUDIO = "girl:meet:studio";

    // MeetClinicTry.lua: MeetClinic
    constexpr const char* GIRL_MEET_CLINIC = "girl:meet:clinic";

    // GirlLostGamble.lua: LostOwnGamble
    constexpr const char* GIRL_GAMBLING_LOST_OWN = "girl:gambling-lost:own";

    // GirlLostGamble.lua: LostRivalGamble
    constexpr const char* GIRL_GAMBLING_LOST_RIVAL = "girl:gambling-lost:rival";

    // SexText.lua: GetAnalMessage
    constexpr const char* GIRL_SEX_ANAL = "girl:sex:anal";

    // SexText.lua: GetGroupMessage
    constexpr const char* GIRL_SEX_GROUP = "girl:sex:group";

    // SexText.lua: GetBDSMMessage
    constexpr const char* GIRL_SEX_BDSM = "girl:sex:bdsm";

    // SexText.lua: GetBestialityMessage
    constexpr const char* GIRL_SEX_BEAST = "girl:sex:beast";

    // SexText.lua: GetLesMessage
    constexpr const char* GIRL_SEX_LESBIAN = "girl:sex:lesbian";

    // SexText.lua: GetNormalMessage
    constexpr const char* GIRL_SEX_NORMAL = "girl:sex:normal";

    // SexText.lua: GetStripMessage
    constexpr const char* GIRL_SEX_STRIP = "girl:sex:strip";

    // SexText.lua: GetHandjobMessage
    constexpr const char* GIRL_SEX_HAND = "girl:sex:hand";

    // SexText.lua: GetTittyMessage
    constexpr const char* GIRL_SEX_TITTY = "girl:sex:titty";

    // SexText.lua: GetOralMessage
    constexpr const char* GIRL_SEX_ORAL = "girl:sex:oral";

    // SexText.lua: GetFootMessage
    constexpr const char* GIRL_SEX_FOOT = "girl:sex:foot";

    // DefaultInteract.lua: InteractDungeon
    constexpr const char* GIRL_INTERACT_DUNGEON = "girl:interact:dungeon";

    // DefaultInteract.lua: InteractBrothel
    constexpr const char* GIRL_INTERACT_BROTHEL = "girl:interact:brothel";

    // Office.lua: InteractOffice
    constexpr const char* GIRL_INTERACT_OFFICE = "girl:interact:office";

    // PrivateChambers.lua: PrivateChambers
    constexpr const char* GIRL_INTERACT_PRIVATE = "girl:interact:private";

    // Bedroom.lua: VisitBedroom
    constexpr const char* GIRL_INTERACT_BEDROOM = "girl:interact:bedroom";

    // Chat.lua: ChatDungeon
    constexpr const char* GIRL_CHAT_DUNGEON = "girl:chat:dungeon";

    // Chat.lua: ChatBrothel
    constexpr const char* GIRL_CHAT_BROTHEL = "girl:chat:brothel";

    // DefaultInteract.lua: Refuse
    constexpr const char* GIRL_REFUSE = "girl:refuse";

    // Mission.lua: GoOnMission
    constexpr const char* GIRL_MISSION = "girl:mission";

    // Training.lua: Training
    constexpr const char* GIRL_TRAINING = "girl:training";

    // Bedroom/PleasureHer.lua: FingerHer
    constexpr const char* GIRL_BEDROOM_FINGER = "girl:bedroom:finger";

    // Bedroom/PleasureHer.lua: EatHerOut
    constexpr const char* GIRL_BEDROOM_LICK = "girl:bedroom:lick";

    // Bedroom/Lesbian.lua: LesbianSex
    constexpr const char* GIRL_BEDROOM_LESBIAN = "girl:bedroom:lesbian";

    // Bedroom/Group.lua: FFMSex
    constexpr const char* GIRL_BEDROOM_FFM = "girl:bedroom:ffm";

    // Bedroom/Group.lua: MMFSex
    constexpr const char* GIRL_BEDROOM_MMF = "girl:bedroom:mmf";

    // Bedroom/Group.lua: OrgySex
    constexpr const char* GIRL_BEDROOM_ORGY = "girl:bedroom:orgy";

    // Bedroom.lua: Blowjob
    constexpr const char* GIRL_BEDROOM_BLOWJOB = "girl:bedroom:blowjob";

    // Bedroom.lua: Deepthroat
    constexpr const char* GIRL_BEDROOM_DEEPTHROAT = "girl:bedroom:deepthroat";

    // Bedroom.lua: Tittyfuck
    constexpr const char* GIRL_BEDROOM_TITTY = "girl:bedroom:titty";

    // Bedroom.lua: AnalSex
    constexpr const char* GIRL_BEDROOM_ANAL = "girl:bedroom:anal";

    // Bedroom.lua: BeastSex
    constexpr const char* GIRL_BEDROOM_BEAST = "girl:bedroom:beast";

    // Bedroom.lua: MasturbateSex
    constexpr const char* GIRL_BEDROOM_MAST = "girl:bedroom:mast";

    // Bedroom.lua: BDSMSex
    constexpr const char* GIRL_BEDROOM_BDSM = "girl:bedroom:bdsm";

    // Bedroom.lua: NormalSex
    constexpr const char* GIRL_BEDROOM_SEX = "girl:bedroom:sex";

    // Bedroom.lua: Strip
    constexpr const char* GIRL_BEDROOM_STRIP = "girl:bedroom:strip";

    // Bedroom/Bathing.lua: Bathing
    constexpr const char* GIRL_BEDROOM_BATHING = "girl:bedroom:bathing";

    // Mission.lua: Quest
    constexpr const char* GIRL_QUEST = "girl:quest";

    // Quests.lua: TavernQuest
    constexpr const char* GIRL_QUEST_TAVERN = "girl:quest:tavern";

    // Quests.lua: ChurchQuest
    constexpr const char* GIRL_QUEST_CHURCH = "girl:quest:church";

    // Quests.lua: StreetsQuest
    constexpr const char* GIRL_QUEST_STREETS = "girl:quest:streets";

    // FreeTime.lua: TakeBath
    constexpr const char* GIRL_FREE_TIME_BATH = "girl:free-time:bath";

    // FreeTime.lua: StayInBed
    constexpr const char* GIRL_FREE_TIME_BED = "girl:free-time:bed";

    // FreeTime.lua: GoToChurch
    constexpr const char* GIRL_FREE_TIME_CHURCH = "girl:free-time:church";

    // FreeTime.lua: FreeTimeCooking
    constexpr const char* GIRL_FREE_TIME_COOKING = "girl:free-time:cooking";

    // FreeTime.lua: WindowShopping
    constexpr const char* GIRL_FREE_TIME_WINDOW_SHOPPING = "girl:free-time:window-shopping";

    // FreeTime.lua: Salon
    constexpr const char* GIRL_FREE_TIME_SALON = "girl:free-time:salon";

    // FreeTime.lua: Picnic
    constexpr const char* GIRL_FREE_TIME_PICNIC = "girl:free-time:picnic";

    // FreeTime.lua: Concert
    constexpr const char* GIRL_FREE_TIME_CONCERT = "girl:free-time:concert";

    // FreeTime.lua: WorkOut
    constexpr const char* GIRL_FREE_TIME_WORK_OUT = "girl:free-time:work-out";

    // FreeTime.lua: Hobby
    constexpr const char* GIRL_FREE_TIME_HOBBY = "girl:free-time:hobby";

    // FreeTime.lua: Movie
    constexpr const char* GIRL_FREE_TIME_MOVIE = "girl:free-time:movie";

}
